Part-I Numpy Questions
Objective:
To build a strong foundation in using NumPy for numerical computations,
including creating arrays, performing operations, and leveraging its
powerful functionalities.

Task 1: Creating Arrays
1. Write a Python program to:
--> Create a 1D NumPy array of 10 integers ranging from 1 to 10.
--> Create a 2D NumPy array of shape (3, 3) with integers from 1 to 9.
--> Create a 3D NumPy array with random floating-point numbers of shape (3, 5, 3).
2. Display the shape, size, and datatype of each array

In [1]:
import numpy as np
l1=np.random.randint(1,11,10)
print(l1.shape)
print(l1.size)
print(type(l1))
l1


(10,)
10
<class 'numpy.ndarray'>


array([10,  8,  3,  1,  3,  8, 10,  6,  4,  2])

In [2]:
import numpy as np
l2=np.random.randint(1,10,9).reshape(3,3)
print(l2.shape)
print(l2.size)
print(type(l2))
l2

(3, 3)
9
<class 'numpy.ndarray'>


array([[3, 1, 4],
       [6, 9, 6],
       [6, 9, 1]])

In [3]:
import numpy as np
l3=np.random.rand(3,5,3)
print(l3.shape)
print(l3.size)
print(type(l3))
l3

(3, 5, 3)
45
<class 'numpy.ndarray'>


array([[[0.52282266, 0.99972967, 0.38109164],
        [0.7626661 , 0.6818483 , 0.0057706 ],
        [0.4112859 , 0.69609923, 0.2267573 ],
        [0.79959381, 0.76059472, 0.15441673],
        [0.01983729, 0.02487364, 0.0073587 ]],

       [[0.23641681, 0.92253536, 0.44588973],
        [0.04711062, 0.23342112, 0.98623127],
        [0.00428653, 0.14226492, 0.35412724],
        [0.88311804, 0.74573824, 0.96948627],
        [0.67741079, 0.11400793, 0.17073483]],

       [[0.42670688, 0.3197871 , 0.46675823],
        [0.41695698, 0.22005472, 0.58872609],
        [0.49836232, 0.84916603, 0.17776149],
        [0.16506833, 0.92542967, 0.91937926],
        [0.57555174, 0.38575608, 0.09312733]]])

Task 2: Array Indexing and Slicing:-

1. Create a NumPy array from the following list:
-->data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
2. Write a Python program to:
-->Retrieve the first three elements of the array.
-->Retrieve every alternate element of the array.
-->Reverse the array.
3. Perform the above operations and display the results

In [3]:
import numpy as np
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
l1=np.array(data)
print(l1[0:3])
print(l1[::2])
print(l1[::-1])


[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


Task 3: Mathematical Operations:-
1. Create two NumPy arrays, A and B, each with 5 random integers between 1 and 20.

2. Write a Python program to:-

--> Add, subtract, multiply, and divide the two arrays element-wise.
--> Compute the dot product of the arrays.
--> Find the mean, median, standard deviation, and variance o--> array A.
--> Identify the maximum and minimum values in array B and their indices

In [4]:
# Add, subtract, multiply, and divide the two arrays element-wise.
import numpy as np
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(A)
print(B)
add=A+B
sub=A-B
mul=A*B
div=A/B
print("Addition :",add)
print("Subtraction :",sub)
print("Multiplication :",mul)
print("Division:",div)

[16  2 12  9  8]
[ 6 19 19  2 12]
Addition : [22 21 31 11 20]
Subtraction : [ 10 -17  -7   7  -4]
Multiplication : [ 96  38 228  18  96]
Division: [2.66666667 0.10526316 0.63157895 4.5        0.66666667]


In [ ]:
# Evaluate the dot product of the array.
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(A)
print(B)
dotProduct = np.dot(A, B)
# Or alternatively: Dot product = A @ B
print(dotProduct)


[10 10  7 15 14]
[ 4 13  8  6 19]
582


In [ ]:
# Find mean, median, standard deviation, and variance o --> array A.
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(A)
print("Mean :",np.mean(A))
print("Median :",np.median(A))
print("Standard deviation :",np.std(A))
print("Varience :",np.var(A))


[ 4 19 16  8  8]
Mean : 11.0
Median : 8.0
Standard deviation : 5.585696017507576
Varience : 31.2


In [8]:
# Identify the maximum and minimum values in array B and their indices
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(B)
print("Maximum :",np.max(B))
print("Minimum :",np.min(B))
print("Maximum idx :",np.argmax(B))
print("Minimum idx :",np.argmin(B))

[11  8  2  8 16]
Maximum : 16
Minimum : 2
Maximum idx : 4
Minimum idx : 2


Task 4: Reshaping and Transposing
1. Create a 1D NumPy array of 12 integers ranging from 1 to 12.
2. Write a Python program to:
-->Reshape the array into a 2D array of shape (4, 3).
-->Reshape the array into a 3D array of shape (2, 2, 3).
-->Transpose the reshaped 2D array and display its shape.

In [7]:
import numpy as np

l1=np.random.randint(1,12,12)
print(l1)
print("2D Array of Size 4X3")
print(l1.reshape(4,3))
print("3D Array of Size 2X2X3  ")
print(l1.reshape(2,2,3))
print("Transpose of 2D Array")
print(np.transpose(l1.reshape(4,3)))
print("Transpose of 2D Array and its shape")
print(np.transpose(l1.reshape(4,3)).shape)


[11  3  9  9  2  1  6  2  5  9  7  2]
2D Array of Size 4X3
[[11  3  9]
 [ 9  2  1]
 [ 6  2  5]
 [ 9  7  2]]
3D Array of Size 2X2X3  
[[[11  3  9]
  [ 9  2  1]]

 [[ 6  2  5]
  [ 9  7  2]]]
Transpose of 2D Array
[[11  9  6  9]
 [ 3  2  2  7]
 [ 9  1  5  2]]
Transpose of 2D Array and its shape
(3, 4)


Task 5: Boolean Masking and Filtering:-

1. Create a NumPy array with 15 random integers between 10 and 50.
2. Write a Python program to:
-->Find all elements greater than 25.
-->Replace all elements less than 30 with 0.
-->Count the number of elements divisible by 5.

In [8]:
import numpy as np

l2=np.random.randint(10,50,15)
print(l2)
print("Numbers Greater than 25 :")
print(l2[l2>25])
print("Replacing all elements less than 30 with 0 :")
l2[l2<30]=0
print(l2)
print("number of nonZero elements divisible by 5")
print(np.count_nonzero(l2[l2%5==0]))
print("number of  elements divisible by 5")
print(np.count_nonzero(l2%5==0))


[34 44 11 46 11 38 37 28 19 34 22 39 24 38 12]
Numbers Greater than 25 :
[34 44 46 38 37 28 34 39 38]
Replacing all elements less than 30 with 0 :
[34 44  0 46  0 38 37  0  0 34  0 39  0 38  0]
number of nonZero elements divisible by 5
0
number of  elements divisible by 5
7


Task 6: Working with Built-in Functions:-

1. Use NumPy's built-in functions to:
-->Create an array of 10 equally spaced values between 0 and 1.
-->Create an identity matrix of size 4x4.
-->Generate a 1D array of 20 random integers between 1 and 100, sort it, and find the 5 largest elements.

In [9]:
# Create an array of 10 equally spaced values between 0 and 1.
import numpy as np
l1=np.linspace(0,1,10)
print("Array of 10 equally spaced values between 0 and 1 \n")
print(l1)

Array of 10 equally spaced values between 0 and 1 

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [10]:
# Create an identity matrix of size 4x4.
import numpy as np
print(np.eye(4,dtype="int"))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [11]:
# Generate a 1D array of 20 random integers between 1 and 100, sort it, and find the 5 largest elements.

import numpy as np
l3=np.random.randint(1,100,20)
print("Original Array :-")
print(l3)
print("Sorted Array :-")
print(np.sort(l3))
print("5 largest elements")
print(np.sort(l3)[-5:][::-1])

Original Array :-
[15 98 83 65  1 65 37 90 38 40 12 89 96 39 99 57 67 34 16 67]
Sorted Array :-
[ 1 12 15 16 34 37 38 39 40 57 65 65 67 67 83 89 90 96 98 99]
5 largest elements
[99 98 96 90 89]


Task 7: Generic:-

1. Create a Python program that:
-->Generates two large random arrays of size (100, 100).
-->Performs matrix multiplication on the two arrays.
-->Finds the determinant and inverse of the resulting matrix (if possible).
-->Measures the time taken to complete these operations.

In [16]:
import numpy as np
import time

# Step 1: Generate two random 100x100 arrays
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

# Step 2: Start the timer
start_time = time.time()
print(f"Operation Start time :{start_time} \n")

# Step 3: Matrix multiplication
C = np.dot(A, B)
print("Matrix multiplication completed.\n")
print(C,"\n")


# Step 4: Calculate determinant
det_C = np.linalg.det(C)
print(f"Determinant of the result: {det_C} \n")


# Step 5: Try to calculate inverse if determinant is not zero
if np.isclose(det_C, 0):
    inverse_C = None
    invertible = False
else:
    inverse_C = np.linalg.inv(C)
    invertible = True

# Step 6: End the timer
end_time = time.time()
print(f"Operation end time :{end_time} \n")

operationtime = end_time - start_time

# Step 7: Print results
print("Matrix is invertible." if invertible else "Matrix is not invertible.")
if invertible:
    print("Inverse matrix calculated successfully.")
    print(inverse_C,"\n")
print(f"Time taken: {operationtime:.4f} seconds")


Operation Start time :1752425379.195773 

Matrix multiplication completed.

[[21.75399327 20.36340888 23.30067232 ... 23.59167258 22.41250531
  22.32949586]
 [25.6837068  25.29882732 26.07649043 ... 26.75327959 26.37715329
  24.98034235]
 [23.55162121 22.1793393  24.01140904 ... 25.53651203 24.52247255
  23.25683562]
 ...
 [23.30194424 23.27018632 22.99405875 ... 24.75863679 24.20947525
  23.33277814]
 [24.05590866 23.40148562 23.66693868 ... 26.10955322 26.62555296
  24.63028681]
 [26.96790402 25.59493582 26.23453418 ... 26.6366106  27.31808989
  26.34742146]] 

Determinant of the result: 1.4268655448370525e+50 

Operation end time :1752425379.19808 

Matrix is invertible.
Inverse matrix calculated successfully.
[[-1.28677370e-02 -9.37369124e-01  6.60189695e-01 ... -1.94028104e-01
   1.87337566e-01 -9.79801642e-02]
 [-2.72365909e+00  6.70567121e+00  1.86587825e+00 ... -2.34153153e+00
   2.00942864e+00 -1.76475698e+00]
 [-4.16567294e+00  1.03699312e+01  1.65987980e+00 ... -3.46140106e+